### ISSUE TITLE
How can i copy the docker container

### ISSUE THREAD

**Issue by WINRARisyou** [Inglan2/LinuxOnGitpod#1]
Great work you've done here, but how can I copy the docker container so I can have a local copy of it. Totally fine if you don't want to share it. Again, great work.

**Comment by Inglan2** [comment]
I dont know what i did with the Dockerfile and stuff but i got most of the code from [3kh0/desktoponcodespaces](https://github.com/3kh0/DesktopOnCodespaces). I am working on a different version and will probably opensource the dockerfile

**Comment by WINRARisyou** [comment]
thx for the clarification
